[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "smt4modplant"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "z3-solver",
]

[project.scripts]
smt4modplant = "SMT4ModPlant.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["src/SMT4ModPlant"]
